# -*- coding: utf-8 -*-
"""Código_MLAM_Sprint1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgA4eCMIiHb617thtpaEq4Q-eKyoLtTZ
"""

import pandas as pd


# 1) CARREGAR BASES

orders = pd.read_csv("/content/olist_order_reviews_dataset.csv")
items = pd.read_csv("/content/olist_order_items_dataset.csv")
reviews = pd.read_csv("/content/olist_orders_dataset.csv")


# 2) JUNTAR AS BASES

df = items.merge(orders, on="order_id", how="inner")
df = df.merge(reviews, on="order_id", how="left")


# 3) LIMPEZA BÁSICA

df = df.dropna(subset=["price"])
df = df.dropna(subset=["review_score"])

# Criando variável ordinal por faixa de preço (baixo, médio, alto)
df["faixa_preco"] = pd.qcut(df["price"], q=3, labels=["Baixo", "Médio", "Alto"])

print("Base final gerada com sucesso!")
print("Quantidade de linhas:", len(df))


# 4) TABELA DE FREQUÊNCIA - VARIÁVEL DISCRETA

variavel_discreta = "order_item_id"

freq_abs = df[variavel_discreta].value_counts().sort_index()
freq_rel = df[variavel_discreta].value_counts(normalize=True).sort_index() * 100
freq_abs_acum = freq_abs.cumsum()
freq_rel_acum = freq_rel.cumsum()

tabela_discreta = pd.DataFrame({
    "Frequência": freq_abs,
    "Frequência Relativa (%)": freq_rel.round(2),
    "Frequência Acumulada": freq_abs_acum,
    "Freq. Relativa Acumulada (%)": freq_rel_acum.round(2)
})

print("\n===============================")
print("TABELA DE FREQUÊNCIA (DISCRETA)")
print("===============================")
print(tabela_discreta)

# Insight 1: A maioria dos pedidos possui poucos itens, pois os valores menores de order_item_id são os mais frequentes.
# Insight 2: Valores altos de order_item_id são raros, indicando que compras com muitos itens acontecem poucas vezes.


# 5) TABELA DE FREQUÊNCIA - VARIÁVEL CONTÍNUA

variavel_continua = "price"

classes = 10
intervalos = pd.cut(df[variavel_continua], bins=classes)

freq_abs_c = intervalos.value_counts().sort_index()
freq_rel_c = intervalos.value_counts(normalize=True).sort_index() * 100
freq_abs_acum_c = freq_abs_c.cumsum()
freq_rel_acum_c = freq_rel_c.cumsum()

tabela_continua = pd.DataFrame({
    "Frequência": freq_abs_c,
    "Frequência Relativa (%)": freq_rel_c.round(2),
    "Frequência Acumulada": freq_abs_acum_c,
    "Freq. Relativa Acumulada (%)": freq_rel_acum_c.round(2)
})

print("\n===============================")
print("TABELA DE FREQUÊNCIA (CONTÍNUA)")
print("===============================")
print(tabela_continua)

# Insight 1: Os preços estão concentrados nas faixas mais baixas, mostrando predominância de produtos mais baratos.
# Insight 2: As últimas faixas possuem baixa frequência, indicando produtos caros e possíveis outliers.